export const unidadesDeNegocio = [
  "Club de Playa", "Comercial Corporativa", "Consejero Delegado",
  "Consejo de Administración", "Desarrollo Naútico Integral",
  "Dirección Comercial Hoteles", "Dirección Comercial Parques y Tours",
  "Dirección de Hoteles", "Dirección de Hoteles Xcaret",
  "Direccion de Operación Parques y Tours",
  "Dirección de Parques, Tours y Naviera",
  "Dirección de Planeación Estratégica y Distribución",
  "Dirección General", "Estaciones de Servicio", "Estrategia Corporativa",
  "Estrategia Financiera", "Estrategia y Desarrollo",
  "Estrategia y Desarrollo Corporativo", "Estrategia y Desarrollo Hotel",
  "Estrategia y Desarrollo Hoteles", "Estrategia y Desarrollo Parques",
  "Excursion Travel", "Ferrys", "Hotel La Casa de la Playa",
  "Hotel Xcaret Arte", "Hotel Xcaret México", "La Casona",
  "México Destination Club", "Naviera Xcaret",
  "Planeación Estratégica y Opt de Ingresos", "Polé", "Resort",
  "Unidades Corporativas de Apoyo",
  "Unidades Corporativas de Apoyo Club Vacacional",
  "Unidades Corporativas de Apoyo Hoteles",
  "Unidades Corporativas de Apoyo Resort", "Vicepresidencia",
  "Xavage", "Xcaret", "Xcaret Xailing", "Xel-Há", "Xenotes",
  "Xenses", "Xenses Noche", "Xervigas", "Xibalbá", "Xoximilco",
  "Xplor", "Xplor Fuego", "Xtours", "Yal-Kú"
];

export const departamentos = [
  "Abastecimiento", "Abastecimiento Corporativo", "Activos Fijos",
  "Activos Fijos CDLP", "Activos Fijos Club Vacacional", "Activos Fijos Hotel",
  "Activos Fijos Hoteles", "Activos Fijos HXA", "Activos Fijos HXM",
  "Activos Fijos Parques", "Administración AyB", "Administración Comercial",
  "Administración Comercial Corporativo", "Administración de Construcción",
  "Administración de Personal y Relaciones Laborales",
  "Administración de Seguros y Fianzas", "Adquisición de Clientes",
  "Analíticos y BI", "Área Artística", "Área Técnica", "Áreas Públicas",
  "Atencion al Colaborador", "Atención al Visitante", "Atracción de Talento",
  "Auditoría Interna", "Bienestar Animal", "Bienestar Integral",
  "Bodas y Eventos", "Business Intelligence", "Calidad y Certificaciones",
  "Call Center", "Capital Humano Hoteles", "Cocina General",
  "Comedor de Colaboradores", "Comunicación y Relaciones Públicas",
  "Concierge", "Conservación y Educación", "Construcción", "Contact Center",
  "Contraloria General", "Coordinación de Actividades Recreativas",
  "Coordinación de Alimentos y Bebidas", "Coordinación de Innovación y Desarrollo",
  "Coordinación de Seguridad Integral", "Coordinación de Servicios Generales",
  "Coordinación de Tiendas", "Costos", "CRM", "Cuentas por Cobrar",
  "Cuentas por Pagar", "Cultura para la Sostenibilidad",
  "Customer Experience", "Danzas", "Desarrollo de Aplicaciones",
  "Desarrollo de Negocios", "Desarrollo Técnico", "Dirección Cadena de Suministro",
  "Dirección Comercial", "Dirección Corporativa de Capital Humano",
  "Dirección Corporativa de Talento Humano", "Dirección de Actividades Recreativas",
  "Dirección de Alimentos y Bebidas", "Dirección de Arte y Cultura",
  "Dirección de Business Intelligence", "Dirección de Compliance",
  "Dirección de Comunicación y RSC", "Dirección de Conservación",
  "Dirección de E-Business", "Dirección de Estrategia Corporativa",
  "Dirección de Finanzas", "Dirección de Fotografía",
  "Dirección de Ingeniería y Mantenimiento", "Dirección de Marketing",
  "Dirección de Mercadotecnia", "Dirección de Naviera Xcaret",
  "Dirección de Operaciones", "Dirección de Proyectos",
  "Dirección de Seguridad Integral", "Dirección de Sistemas",
  "Dirección de Sostenibilidad y Relaciones Institucionales",
  "Dirección de Ventas", "Dirección General", "Diseño Gráfico",
  "Diseño Web y Apps", "Diseño y Arte", "Diversidad, Equidad e Inclusión",
  "E-Commerce", "E-Marketing", "Ecología Acuática", "Ecología de Aves",
  "Enfermería", "Entretenimiento", "Facturación", "Ferrys",
  "Finanzas y Control DNI", "Fiscal", "Formación de Talento",
  "Formación y Desarrollo", "Fotografía", "Gerencia de Actividades Recreativas",
  "Gerencia de Alimentos y Bebidas", "Gerencia de Ama de Llaves",
  "Gerencia de Ambientación de Paisaje", "Gerencia de Calidad",
  "Gerencia de Contact Center", "Gerencia de Ingeniería y Mantenimiento",
  "Gerencia de Operaciones", "Gerencia de Recepción",
  "Gerencia de Seguridad Integral", "Gerencia de Tiendas",
  "Gerencia de Ventas Club Vacacional", "Gestión de Proyectos",
  "Gestión de Talento", "Gestión Empresarial", "Gobernanza de Datos",
  "Gobernanza de TI", "Grupos y Convenciones", "Guardavidas", "Gym",
  "Imagen y Diseño", "Ingeniería y Mantenimiento Parques", "Ingresos",
  "Instalaciones", "Jurídico Ambiental", "Lavandería", "Legal y Jurídico",
  "Mantenimiento", "Mantenimiento a Embarcaciones", "Marca y Redes Sociales",
  "Mercadotecnia", "Mesa de Ayuda y Soporte Técnico", "Nóminas",
  "Obras y Proyectos", "Operación", "Organización y Compensación",
  "Planeación Comercial", "Planeación Estratégica e Innovación",
  "Planeación Financiera", "Prevención y Protección", "Procesos de Negocio",
  "Producción Audiovisual", "Producción y Operación", "Proyectos de Sistemas",
  "Publicidad", "Recepción", "Relaciones Laborales", "Reservaciones",
  "Revenue Management", "Salud Animal", "Salud Laboral",
  "Seguridad de la Información", "Servicios Audiovisuales",
  "Sistemas y Desarrollo", "Soporte de Aplicaciones",
  "Subdirección de Calidad Parques y Tours", "Subdirección de Contact Center",
  "Subdirección de Ingeniería y Mantenimiento", "Subdirección de Ingresos",
  "Subdirección de Mercadotecnia", "Subdirección de Revenue Managment",
  "Subdirección de Sostenibilidad", "Talento Humano",
  "Tecnología de La Información y Comunicaciones", "Tecnología Hoteles",
  "Tesorería", "Transporte de Personal", "Urbanización", "Ventas A Bordo",
  "Ventas Latam y Europa", "Ventas USA y Cánada"
];

export const puestos = [
  "Abogado", "Acuaguía", "Administrador", "Agente", "Albañil",
  "Alberquero", "Almacenista", "Amazonas", "Analista", "Anfitrión",
  "Animador", "Arquitecto", "Artesano", "Artista", "Asesor", "Asistente",
  "Auditor", "Auxiliar", "Ayudante", "Bailarín", "Botones", "Buffetero",
  "Buzo", "Cabo", "Cajero", "Camarista", "Cantante", "Cantinero",
  "Capitán", "Capturista", "Caracterizador", "Cargador", "Carnicero",
  "Carpintero", "Chef", "Chofer", "Cocinero", "Comprador", "Concierge",
  "Consultor", "Contador", "Contralor", "Coordinación", "Costurera",
  "Curador", "Desarrollador", "Designer", "Dibujante", "Dirección",
  "Diseñador", "Dj", "Docente", "Editor", "Ejecutivo", "Electricista",
  "Encargado", "Especialista", "Estilista", "Facturista", "Fotógrafo",
  "Garrotero", "Gerencia", "Gestor", "Guardavidas", "Guardia", "Guía",
  "Herrero", "Hostess", "Ingeniero", "Inspector", "Instructor",
  "Intendente", "Jefatura", "Lavador", "Líder", "Maestro", "Marinero",
  "Mecánico", "Mensajero", "Mesero", "Mixólogo", "Motorista", "Músico",
  "Oficial", "Operador", "Panadero", "Paramédico", "Pastelero",
  "Piloto", "Pintor", "Plomero", "Portero", "Promotor", "Quality",
  "Recepcionista", "Remero", "Reservacionista", "Responsable",
  "Runner", "Sastre", "Soldador", "Sommelier", "Soporte", "Técnico",
  "Terapeuta", "Transportador", "Velador", "Vendedor", "Veterinario",
  "Vicepresidencia", "Videógrafo", "Volador"
];

export const tiposUnidad = ["Parque", "Hotel"];

export const colaboradoresDemo = [
  { id: 1, codigo: "01", nombre: "Juan", unidadNegocio: "Xelha", area: "Mesa de Ayuda y Soporte Técnico", puesto: "Ingeniero", horario: "08:00–17:00", guardia: "Sábados", activo: true },
  { id: 2, codigo: "02", nombre: "Matha", unidadNegocio: "Xcaret", area: "Dirección de Sistemas", puesto: "Jefatura", horario: "08:00–17:00", guardia: "Domingos", activo: true },
  { id: 3, codigo: "03", nombre: "Dulce", unidadNegocio: "Xcaret", area: "Mesa de Ayuda y Soporte Técnico", puesto: "Ingeniero", horario: "10:00–19:00", guardia: "Ninguna", activo: true },
  { id: 4, codigo: "0", nombre: "Jesus", unidadNegocio: "Xcaret", area: "Mesa de Ayuda y Soporte Técnico", puesto: "Ingeniero", horario: "08:00–17:00", guardia: "Ninguna", activo: true },
  { id: 5, codigo: "05", nombre: "Daniel", unidadNegocio: "Xcaret", area: "Mesa de Ayuda y Soporte Técnico", puesto: "Ingeniero", horario: "08:00–17:00", guardia: "Ninguna", activo: true },
];

export const incidenciasDemo = [
  { id: 1, colaboradorId: 3, nombre: "Jesus", tipo: "Vacaciones", fechaInicio: "2026-06-02", fechaFin: "2026-06-06", estatus: "Pendiente" },
  { id: 2, colaboradorId: 4, nombre: "Dulce", tipo: "Permiso", fechaInicio: "2026-06-10", fechaFin: "2026-06-10", estatus: "Pendiente" },
  { id: 3, colaboradorId: 5, nombre: "Daniel", tipo: "Justificante", fechaInicio: "2026-05-26", fechaFin: "2026-05-26", estatus: "Aprobado" },
];

export const asistenciaDemo = [
  { colaboradorId: 1, fecha: "2026-06-20", entrada: "07:52", salida: "17:05", estado: "A" },
  { colaboradorId: 1, fecha: "2026-06-19", entrada: "08:10", salida: "17:00", estado: "R" },
  { colaboradorId: 2, fecha: "2026-06-20", entrada: "08:00", salida: "17:00", estado: "A" },
  { colaboradorId: 3, fecha: "2026-06-20", entrada: null, salida: null, estado: "F" },
  { colaboradorId: 4, fecha: "2026-06-20", entrada: "08:05", salida: "17:00", estado: "A" },
  { colaboradorId: 5, fecha: "2026-06-20", entrada: "08:00", salida: "17:00", estado: "A" },
];

